CREATE TABLE AppWeb.Usuarios(Id_Usuarios INT AUTO_INCREMENT NOT NULL PRIMARY KEY, NombreUser VARCHAR(55) NOT NULL, 
ApellidoP VARCHAR(55) NOT NULL, ApellidoM VARCHAR(55) NOT NULL, TelefonoUser VARCHAR(55) NOT NULL, EmailUser VARCHAR(255) NOT NULL, 
Tusuario INT NOT NULL, UserNick VARCHAR(55) NOT NULL, PasswordUser VARCHAR(255) NOT NULL)ENGINE = INNODB;